FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN pip install streamlit
CMD ["streamlit", "run", "--server.address", "0.0.0.0", "--server.port", "8051", "resume_analyser.py"]

