FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 5000
RUN mkdir chroma_data && mkdir pdfs_posted
CMD ["python3.12", "secure_resume_api.py"]

